name: flutter_crud_app
description: App Flutter CRUD para clientes e produtos.
publish_to: 'none' # NÃ£o publicar no pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^0.8.9
  image_picker_for_web: ^2.2.0
  flutter_lints: ^2.0.3
  characters: ^1.4.0
  matcher: ^0.12.17
  material_color_utilities: ^0.11.1
  meta: ^1.16.0
  mime: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  test_api: ^0.7.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholder.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
